var Config = {
	WEBPORT : 4223,
	CONTROLLERPORT : 4222,
	SERVER_NAME : "localhost",
	BIRD_FRAME_WIDTH : 58,
	BIRD_FRAME_HEIGHT : 40,
	CANVAS_WIDTH : "1000",
	CANVAS_HEIGHT : "700",
	FLAP_VELOCITY : 5,
	FORWARD_VELOCITY : 10,
	ACCELERATION : 9,
	GROUND_HEIGHT : 80,
	TUBE_WIDTH : 80,
	SERVER_INTERVAL : 50,
}

global.Config = Config;